steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/aquabyte-409714/wally/strive-wally-registry-backend:$COMMIT_SHA', '-f', 'wally-registry-backend/Dockerfile', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/aquabyte-409714/wally/strive-wally-registry-backend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "wally-backend",
        "--image",
        'us-east4-docker.pkg.dev/aquabyte-409714/wally/strive-wally-registry-backend:$COMMIT_SHA',
        "--region",
        "us-east4",
        "--platform",
        "managed",
        "--command",
        "./launch",
        "--allow-unauthenticated",
      ]

timeout: 900s
options:
 machineType: 'E2_HIGHCPU_8'
 default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
